---
- name: create dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcpd.conf
  register: dhcpd
  
- name: restart dhcpd if needed
  service:
    name: dhcpd
    state: restarted
  when: dhcpd.changed

- name: start dhcpd if needed
  service:
    name: dhcpd
    state: started
