---
- name: see if rc.conf.local exists
  stat:
    path: /etc/rc.conf.local
  register: rc_conf_local

- name: create rc.conf.local if necessary
  copy: 
   src: /etc/rc.conf 
   dest: /etc/rc.conf.local
  when: rc_conf_local.stat.exists == False

- name: configure rc.conf.local vmd flag
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: "^vmd_flags="
    line: "vmd_flags="

- name: create input for dhcpd flags
  set_fact: 
    dhcpd_flags_input: "{{ lookup('template', 'dhcpd.flags.j2') }}"

- name: configure rc.conf.local dhcpd flags
  lineinfile: 
    dest: /etc/rc.conf.local
    regexp: "^dhcpd_flags="
    line: "{{ dhcpd_flags_input }}"
