- name: configure /etc/localtime
  file:
    src: "{{ tz }}"
    dest: "/etc/localtime"
    state: link
    force: yes
  register: tz_changed
  
- name: kick ntpd if needed
  command: ntpd -s
  when: tz_changed.changed
